spring.application.name=backend

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Use ENV variables (IMPORTANT)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Local Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/deshizaiqa
#spring.datasource.username=postgres
#spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
