spring.application.name=backend
# ------------------------------
# MySQL Database Configuration
# ------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/deshizaiqa
spring.datasource.username=postgres
spring.datasource.password=root

# ------------------------------
# JPA / Hibernate Configuration
# ------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect